replicaCount: 1

app: bitcoin-streamer-orion
env: mainnet

image:
  repository: asia-south1-docker.pkg.dev/router-mainnet-api/router-apps-asia-south/bitcoin-streamer
  tag: latest
  pullPolicy: IfNotPresent

container:
  secretName: btc-streamer-orion-env

service:
  type: NodePort
  name: bitcoin-streamer-orion
  port: 8903
  targetPort: 8903

sslcert:
  enabled: true
  name: "bitcoin-streamer-orion-tls"
  host: "api.btc-streamer-orion.routerchain.network"
  annotations:
    "helm.sh/resource-policy": "keep"

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 80
  minReplicas: 1
  maxReplicas: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1: "managed-certificates"
    "helm.sh/resource-policy": "keep"

backendConfig:
  healthCheck:
    requestPath: /
    checkIntervalSec: 60
    timeoutSec: 100
    healthyThreshold: 1
    unhealthyThreshold: 5

resources:
  requests:
    memory: "2048Mi"
    cpu: "1"
  limits:
    memory: "6000Mi"
    cpu: "2"
